services:
  backend-api:
    build:
      context: .
      dockerfile: src/ProductManagement.API/Dockerfile
    container_name: product-management-api
    ports:
      - "5187:5187"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:5187
      - JwtSettings__Secret=${JWT_SECRET:-SuperSecretKeyForProductManagementApiAssessment2026!#*$}
      - AllowedOrigins__0=${FRONTEND_ORIGIN:-http://localhost:3000}
    restart: unless-stopped

  frontend-web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    container_name: product-management-web
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    restart: unless-stopped
